### ISSUE TITLE
Table of Props not showing up

### ISSUE THREAD

**Issue by Agusnez** [Aaron-Pool/Vue-Cli-Storybook-Docs#1]
Hello,

In a fresh install when trying to add the table of props, doesn't work. It says: `Cannot read property '_c' of undefined`

I'm trying to add the table by using the `<Props of=MyButton/>` (previously added demo props in MyButton for the demo).

Has anyone encountered this issue? Thanks!

**Comment by Aaron-Pool** [comment]
Could you provide the storybook version you're running, as well as the story file that is throwing the error?

**Comment by Aaron-Pool** [comment]
Closing this, due to lack of response. I'm assuming that the version update fixed your issue.
